class DynamicReviewsPanel{constructor(){this.apiBaseUrl='/api';this.updateInterval=30000;this.retryAttempts=3;this.retryDelay=1000;this.isUpdating=false;this.init();}
init(){console.log('🚀 Iniciando painel dinâmico de reviews...');this.updateReviewsStats();setInterval(()=>{if(!this.isUpdating){this.updateReviewsStats();}},this.updateInterval);this.observeDOM();}
async updateReviewsStats(){if(this.isUpdating)return;this.isUpdating=true;console.log('📊 Atualizando estatísticas dos reviews...');try{const stats=await this.fetchReviewsStats();if(stats){this.updatePanelElements(stats);console.log(`✅ Stats atualizados:${stats.average_rating}⭐(${stats.total_reviews}reviews)`);}}catch(error){console.error('❌ Erro ao atualizar stats:',error);}finally{this.isUpdating=false;}}
async fetchReviewsStats(retryCount=0){try{const response=await fetch(`${this.apiBaseUrl}/reviews/stats`,{method:'GET',headers:{'Content-Type':'application/json','Cache-Control':'no-cache'}});if(!response.ok){throw new Error(`HTTP ${response.status}:${response.statusText}`);}
const data=await response.json();return data;}catch(error){console.error(`❌ Erro ao buscar stats(tentativa ${retryCount+1}):`,error);if(retryCount<this.retryAttempts-1){await this.sleep(this.retryDelay*(retryCount+1));return this.fetchReviewsStats(retryCount+1);}
return{average_rating:4.8,total_reviews:47,rating_distribution:{"5":40,"4":5,"3":1,"2":1,"1":0},source:"fallback"};}}
updatePanelElements(stats){this.updateElement('.reviews-average-rating, .average-rating, [data-rating]',stats.average_rating);this.updateElement('.reviews-total, .total-reviews, [data-total]',stats.total_reviews);this.updateStarsDistribution(stats.rating_distribution);this.updateLastUpdated(stats.last_updated);this.addDynamicIndicator(stats.source);}
updateElement(selector,value){const elements=document.querySelectorAll(selector);elements.forEach(element=>{if(element){if(typeof value==='number'){if(element.classList.contains('rating')||element.getAttribute('data-rating')){element.textContent=value.toFixed(1);}else{element.textContent=value.toLocaleString('pt-BR');}}else{element.textContent=value;}}});}
updateStarsDistribution(distribution){const starElements=document.querySelectorAll('[data-stars]');starElements.forEach(element=>{const starCount=element.getAttribute('data-stars');const count=distribution[starCount]||0;element.textContent=count;});}
updateLastUpdated(timestamp){if(!timestamp)return;const elements=document.querySelectorAll('.last-updated, [data-last-updated]');elements.forEach(element=>{if(element){const date=new Date(timestamp);const formattedDate=date.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});element.textContent=`Atualizado em:${formattedDate}`;}});}
addDynamicIndicator(source){const indicators=document.querySelectorAll('.dynamic-indicator, [data-dynamic]');indicators.forEach(indicator=>{if(source==='supabase'){indicator.innerHTML='🔄 <span>Dados em tempo real</span>';indicator.className='dynamic-indicator live';}else{indicator.innerHTML='⚠️ <span>Dados de fallback</span>';indicator.className='dynamic-indicator fallback';}});}
observeDOM(){const observer=new MutationObserver((mutations)=>{mutations.forEach((mutation)=>{if(mutation.type==='childList'&&mutation.addedNodes.length>0){mutation.addedNodes.forEach((node)=>{if(node.nodeType===Node.ELEMENT_NODE){const reviewElements=node.querySelectorAll('[data-rating], [data-total], .reviews-panel');if(reviewElements.length>0){console.log('🔄 Novos elementos de reviews detectados, atualizando...');setTimeout(()=>this.updateReviewsStats(),100);}}});}});});observer.observe(document.body,{childList:true,subtree:true});}
sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
forceUpdate(){console.log('🔄 Atualização forçada solicitada...');this.updateReviewsStats();}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',()=>{window.dynamicReviews=new DynamicReviewsPanel();});}else{window.dynamicReviews=new DynamicReviewsPanel();}
window.DynamicReviewsPanel=DynamicReviewsPanel;console.log('📊 Script de reviews dinâmicos carregado!');


